### ISSUE TITLE
Define how the SIRT plans to engage with the researchers and communities

### ISSUE THREAD

**Issue by u269c** [ossf/SIRT#1]
The SIRT needs to determine how it plans to define both the engagements and services it plans to offer. This means we need clear vision and definitions around:
   - [ ] What types of engagements will the SIRT provide?
   - [ ] What tiers of engagements will the SIRT agree to?
   - [ ] What will handing off to another foundation or SIRT or Security team look like?
   - [ ] What are the known caveats or exceptions we need to be aware of early?

This work should be done in a shared document, lead by @u269c and @TheFoxAtWork

**Comment by TheFoxAtWork** [comment]
Thanks @u269c for opening the issue to capture the work!

**Comment by u269c** [comment]
Starting draft attached (curtesy of @TheFoxAtWork).

https://docs.google.com/document/d/1SXvs_i7ojQ2i-5zU_-GXlsi76KYNva0o583kysY-wtA/edit

**Comment by zmanion** [comment]
I'm in for a side/ad-hoc meeting/group on this issue.

**Comment by SecurityCRob** [comment]
Excellent work helping guide our conversation this week.  I'm looking forward to discussing more as we move forward

**Comment by u269c** [comment]
Can we move this to Section 2 of the SIRT work?

**Comment by ran-dall** [comment]
So I feel like the time has come to start finalizing our SIRT plans, and we have yet to fully define the scope of our plan. I realize that much of this depends on the discussions and interviews that will happen as part of Stream 1; however, we should still have an initial scope to build off our initial set of services for Stream 2.

From the initial discussion I had with maintainers, it would seem pretty unanimous that a good use of the SIRT would be facilitating the communication between researchers/bug finders and upstream projects. 

I propose we start there for the first iteration of our plan, as pretty much all the initial discussions brought this up.

Furthermore, I propose moving this to 1.3 in the Stream 1 plan, as Stream 1 will handle the discussions, surveying, and much of the external communication in the SIRT.
