### ISSUE TITLE
VOTE - OSS-SIRT staffing mode

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/SIRT#11]
Please express your opinion in this ISSUE on which path you think the group develops the plan to:

1.)	Fulltime staff handling all duties of the OSS-SIRT including IR, disclosure, coordination, education that would be augmented by volunteers
2.)	Mostly volunteers staffed by OSSF members that is supported by handful of FTEs for administrative-type tasks that assists projects with IR areas they need assistance on
3.)	Combination of some FTEs and volunteers building out processes and capabilities that predominantly coaches/consults first year of operation after which time  direction is determined (fulltime staff or mostly volunteers). 

We will review the votes in our 18October meeting and have any final conversations before formally documenting the group’s decision and adjusting the plan based off of that choice.

**Comment by TheFoxAtWork** [comment]
2️⃣ or 3️⃣ .  If 3️⃣ then we should ensure some form of rotational training or partnership for volunteers. The skills necessary for a SIRT, especially an open source one, are in short supply.  Anything we can do to increase those skills across communities, especially in open source ecosystems, will uplift the overall responsive success by those ecosystems.

**Comment by ran-dall** [comment]
I agree with everything said by @TheFoxAtWork in the previous comment.

I lean more towards 2️⃣ than 3️⃣; I would like to see how many volunteers and interested parties exist before we start considering  3️⃣ or even 1️⃣.

**Comment by menkhus** [comment]
#2.  I appreciated this idea "Anything we can do to increase those skills across communities, especially in open source ecosystems, will uplift the overall responsive success by those ecosystems"    I believe the experience is valuable to those who contribute, and then bring that to whatever else they do.

**Comment by u269c** [comment]
**Option 2** is my preference.

That being said, it's not clear what your suggestion aims to do. We should tie this to our mission and scope, as detailed in https://github.com/ossf/SIRT/blob/main/README.md.

**Comment by zmanion** [comment]
Assuming this is not yet decided, I'll vote for 1. But this really depends on what we want. If we want a dependable and sufficiently professional reponse for a major vulnerability case, then 1.

I expect that at least some degree of paid full/part-time staff will be needed.

I have no problem with models 2 and 3, depending on what we (or whomever is directing us) want.

**Comment by TheFoxAtWork** [comment]
Voted 4 in favor of a volunteer model with a handful of support staff dtd: TUE OCT 18. On the anniversary of sponsors funding the effort this decision will be revisited. CC @SecurityCRob

**Comment by SecurityCRob** [comment]
on 18October2022 the group discussed and approved the vote for staffing model #2- Mostly volunteers staffed by OSSF members that is supported by handful of FTEs for administrative-type tasks that assists projects with IR areas they need assistance on.

We also agreed that annually on the anniversary date of the sponsors' final approval of the plan this model will be reviewed to ensure it still allows us to be successful in achieving our mission.
