### ISSUE TITLE
SIRT-SIG Mission Statement Proposal

### ISSUE THREAD

**Issue by TheFoxAtWork** [ossf/SIRT#21]
This issue is to capture the need to define a clear mission statement for the SIRT. A proposed draft is below:

The mission of the SIRT is to empower open source security teams and open source projects to be self-sufficient and apply learnings from engagement with the SIRT. The SIRT will respond to open source projects' requests for assistance, guidance, and support in the handling, processing, communications, and general management of suspected and confirmed vulnerabilities and findings reported to them, directly or by proxy in a manner that considers the community’s existing response processes. The SIRT will NOT self-promote engaging a project unless _significant critical concern_ has been expressed by the project’s adopters in the handling and management of reported security concerns.

In the course of serving open source projects, the SIRT will consider all information provided, seek to understand any outside influences or additional factors to be considered prior to engaging, and render a decision on engagement and execution accordingly.

**Comment by u269c** [comment]
The old grumpy program manager in me says `this is too long`.

I'd suggest, without impacting the content:

#### Mission

To empower and coordinate open source security teams and open source software **projects** to be self-sufficient **with respect to handling vulnerabilities in their software**, and **improve itself through lessons learned** from **its engagement**.

#### Our promise to the maintainers and consumers of OSS

The SIRT will respond and collaborate with open source **software** project's requests for assistance, guidance, and support. Through the SIRT's offerings, open source **software** projects may expect to receive helpful and inclusive recommendations or direction in the handling, processing, communications, and general management of suspected and confirmed vulnerabilities and findings reported to them, directly or by proxy in a manner that considers the project's existing response processes.

In the course of serving open source projects, the SIRT will consider all information provided, seek to understand any outside influences or additional factors to be considered prior to engaging, and render a decision on engagement and execution accordingly. The SIRT shall balance the needs and constraints of the projects requesting support, as well as the needs of the consumers of those projects to the practical extent possible.


### Notes:
- **bolded** changes and suggestions
- be specific about "software", just so we do not include hardware (osh) in the scope, unless that is intended. there are variations on Open Source things now :)
- The longer paragraphs are more about what we will do when we engage, so I'd bundle that out of the mission, and into something closer to how we want to operate. **It might also be nice to promise respectful communications** or something along those lines in there, given the position of the foundation.


my 2c,

**Comment by zmanion** [comment]
Editorial/grammar comments/suggestions:

..to empower and coordinate with open source security teams and projects to be self-sufficient...

The SIRT will respond to and collaborate with requests for...

I also favor a more pithy mission statement, but that could be addressed with a complete yet succint first sentence, follwed by detail, as suggested in https://github.com/ossf/SIRT/issues/21#issuecomment-1315472426.

**Comment by SecurityCRob** [comment]
added amended wording to Charter & Readme.md
