### ISSUE TITLE
VOTE - Approved SIG Charter

### ISSUE THREAD

**Issue by SecurityCRob** [ossf/SIRT#34]
SIG members - please review our charter and provide feedback and vote to approve or refuse the document - https://github.com/ossf/SIRT/blob/main/CHARTER.md

Please Express your vote by 7Dec2022.

**Comment by ran-dall** [comment]
+1 ✅ Approve

---

@SecurityCRob There's a syntax error in 2f. I don't know if that last line is supposed to be **bold**.

**Comment by TheFoxAtWork** [comment]
+1 ✅ Approve

**Comment by zmanion** [comment]
+1 ✅ Approve, I also approve of the non-material tweaks in https://github.com/ossf/SIRT/pull/35.

**Comment by SecurityCRob** [comment]
Approved by SIG Vote 7Dec2022
